query GetHome {
	allArtworkdetails {
		artworkCoverImage {
			responsiveImage {
				src
				width
				height
				alt
				title
				sizes
				base64
			}
		}
		artworkTitle
		artworkYear
		artworkSlug
		artworkWriteup {
			value
			links
			blocks
		}
		artworkShortWriteup {
			value
			links
			blocks
		}
	}
}
